name: make blog post
on: [pull_request]
jobs:
  build:
    name: PR to Blog post
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: filter PR merged
      uses: actions/bin/filter@master
      with:
        args: merged true
    - name: pr2md
      uses: vvakame/github-actions/pr-to-md@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --timezone Asia/Tokyo
    - name: md2blog
      uses: vvakame/github-actions/md-to-blogpost@master
      env:
        BLOG_REPO_GITHUB_TOKEN: ${{ secrets.BLOG_REPO_GITHUB_TOKEN }}
      with:
        args: --owner vvakame --name vvakame-blog --timezone Asia/Tokyo result.md
    - name: blog to slack
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: 'PR merged!: {{ EVENT_PAYLOAD.pull_request.html_url }}'
    - name: cat GITHUB_EVENT_PATH
      uses: actions/bin/sh@master
      with:
        args: '"cat ${{ github.event_path }}"'
